#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os.path

from java import lexer
from java import parser
from java import walker


def transform(filename):
    if not filename:
        args = []
    else:
        args = [filename, ]
    
    L = lexer.Lexer(*args)
    P = parser.Parser(L)
    P.setFilename(L.getFilename())

    try:
        P.compilationUnit()
    except (Exception, ), exc:
       print '*** exception while parsing:'
       print exc
       return 1

    ast = P.getAST()
    if not ast:
       print '*** error: no AST generated.'
       return 2

    W = walker.Walker()
    filein = os.path.basename(filename)
    fileout = '%s.py' % (os.path.splitext(filein)[0])
    print W.module(ast, filein, fileout)
    return 0


if __name__ == '__main__':
    import sys
    import psyco
    psyco.full()

    try:
        name = sys.argv[1]
    except (IndexError, ):
        name = None
    ret = transform(name)
    sys.exit(ret)

